# Works with GRASP v1.1.2

settings:
    strict: true
input: {driver: sdata, file: inversionBACK.sdat}
output:
    segment: {function: classic, stream: bench_inversionRslts.txt}
retrieval:
    general: {path_to_internal_files: /usr/local/share/grasp/kernels/}
    mode: inversion
    inversion:
        regime: single_pixel
        convergence:
            maximum_iterations_for_stopping: 20
            maximum_iterations_of_Levenberg-Marquardt: 20
            minimization_convention: logarithm
            normal_system_solver: sparse_matrix_solver
            scale_for_finite_difference: 3.0e-05 #2.0e-5
            shift_for_applying_logarithm_to_negative_values: 1.1
            threshold_for_stopping: 1.0e-9 #0.001
            threshold_for_stopping_Q_iterations: 1.0e-09 #1.0e-06
        measurement_fitting: {polarization: relative_polarization_components}
        noises:
            noise[1]:
                error_type: relative
                measurement_type[1]:
                    index_of_wavelength_involved: [1, 2, 3]
                    type: I
                standard_deviation: 0.03
                standard_deviation_synthetic: 0.0
            noise[2]:
                error_type: absolute
                measurement_type[1]:
                    index_of_wavelength_involved: [1, 2, 3]
                    type: Q
                measurement_type[2]:
                    index_of_wavelength_involved: [1, 2, 3]
                    type: U
                standard_deviation: 0.005
                standard_deviation_synthetic: 0.0
    forward_model:
        phase_matrix:
            kernels_folder: KERNELS_BASE/
            size_binning_method_for_triangle_bins: logarithm
            number_of_elements: 4
            radius:
                mode[1]: {max: 15.0, min: 0.05}
                mode[2]: {max: 15.0, min: 0.05}
        radiative_transfer:
            absolute_error_rt_calculations: 1.0e-06
            aerosol_profile_vertical_type: gaussian
            molecular_profile_vertical_type: exponential
            number_of_layers: 50
            reference_plane_for_polarization: principal_plane
            simulating_derivatives:
                number_of_fourier_expansion_coefficients: 6
                number_of_gaussian_quadratures_for_expansion_coefficients: 10
                number_of_guassian_quadratures_for_fourier_expansion_coefficients: 20
                order_of_scattering: multiple_scattering
            simulating_observation:
                number_of_fourier_expansion_coefficients: 6
                number_of_gaussian_quadratures_for_expansion_coefficients: 10
                number_of_guassian_quadratures_for_fourier_expansion_coefficients: 20
                order_of_scattering: multiple_scattering

    debug:
        additional_information: false
        verbose: true

    products:
        aerosol:
            chemistry: false
            lidar: true
            optical_properties: true
            particulate_matter: false
            phase_matrix: false
            refractive_index: true
            theoretical_bimodal_extinction: false
            theoretical_bimodal_parameters: false
            type: false
        error_estimation:
            aerosol:
                lidar: false
                optical_properties: false
            parameters: false
        forcing:
            broadband_flux: false
            forcing: false
        retrieval:
            fitting: true
            parameters: true
            residual: true
        surface:
            main_characteristics: true

    constraints:
        characteristic[1]:
            mode[1]:
                initial_guess:
                    index_of_wavelength_involved: [0]
                    max: [1.0] # τfactor should not exceed unity
                    min: [0.00000001]
                    value: [0.001]
            mode[2]:
                initial_guess:
                    index_of_wavelength_involved: [0]
                    max: [5.0]
                    min: [0.00000001]
                    value: [0.002]
            retrieved: true
            type: aerosol_concentration
        characteristic[2]:
            mode[1]:
                initial_guess:
                    index_of_wavelength_involved: [0, 0]
                    max: [0.34, 0.60]
                    min: [0.13, 0.35]
                    value: [0.17, 0.4]
            mode[2]:
                initial_guess:
                    index_of_wavelength_involved: [0, 0]
                    max: [6.0, 0.77]
                    min: [0.65, 0.3]
                    value: [1.0, 0.45]
            retrieved: true
            type: size_distribution_lognormal
        characteristic[3]:
            mode[1]:
                initial_guess:
                    index_of_wavelength_involved: [1]
                    max: [1.6]
                    min: [1.33]
                    value: [1.4]
                single_pixel:
                    smoothness_constraints:
                        difference_order: 2
                        lagrange_multiplier: 0.1
            mode[2]:
                initial_guess:
                    index_of_wavelength_involved: [1]
                    max: [1.6]
                    min: [1.33]
                    value: [1.4]
                single_pixel:
                    smoothness_constraints:
                        difference_order: 2
                        lagrange_multiplier: 0.1
            retrieved: true
            type: real_part_of_refractive_index_spectral_dependent
        characteristic[4]:
            mode[1]:
                initial_guess:
                    index_of_wavelength_involved: [1] 
                    max: [0.01]
                    min: [1e-6]
                    value: [0.002]
                single_pixel:
                    smoothness_constraints:
                        difference_order: 2
                        lagrange_multiplier: 0.1
            mode[2]:
                initial_guess:
                    index_of_wavelength_involved: [1]
                    max: [0.01]
                    min: [1e-6]
                    value: [0.002]
                single_pixel:
                    smoothness_constraints:
                        difference_order: 2
                        lagrange_multiplier: 0.1
            retrieved: true
            type: imaginary_part_of_refractive_index_spectral_dependent
        characteristic[5]:
            type: surface_water_cox_munk_iso
            retrieved: true
            mode[1]:
                initial_guess:                       #1      #2      #3
                    value:                          [0.000000002]
                    min:                            [0.000000001]
                    max:                            [0.000000003]
                    index_of_wavelength_involved:   [1]
                single_pixel:
                    smoothness_constraints:
                        difference_order: 1
                        lagrange_multiplier: 0.0
            mode[2]:
                initial_guess:                       #1      #2      #3
                    value:                          [0.999999]
                    min:                            [0.999998]
                    max:                            [1.000000]
                    index_of_wavelength_involved:   [0]
            mode[3]:
                initial_guess:                       #1      #2      #3
                    value:                          [0.015]
                    min:                            [0.00406] # 1 m/s
                    max:                            [0.040] # 0.027 -> 10 m/s
                    index_of_wavelength_involved:   [0]
        characteristic[6]:
            type: vertical_profile_parameter_height
            retrieved: true
            mode[1]:
                initial_guess:                      #1
                    value:                          [1000.0 ]
                    min:                            [500.0]
                    max:                            [4000.0]
                    index_of_wavelength_involved:   [0      ]
            mode[2]:
                initial_guess:                      #1
                    value:                          [1000.0 ]
                    min:                            [500.0] 
                    max:                            [4000.0]
                    index_of_wavelength_involved:   [0      ]
#        DESERT INSPIRED (lower mins)
        characteristic[7]:
            mode[1]:
                initial_guess:                         #0.091086, 0.12525, 0.20794, 0.25698, 0.4415, 0.49488, 0.53105 , 0.6791  , 0.62972[DESERT]
                    index_of_wavelength_involved: [1] # 0.41 ,    0.443,   0.49 ,   0.555,   0.67 ,  0.865,   1.02 ,    1.65 ,    2.13 μm
                    max:                               [0.2,      0.2,     0.3,     0.4,     0.6,    0.7,     0.8,      1.0,      0.9]
                    min:                               [0.0050,   0.0050,  0.0050,  0.0050,  0.0050, 0.0200,  0.0200,   0.0200,   0.0200]
                    value:                             [0.1000,   0.1000,  0.2000,  0.3000,  0.4000, 0.5000,  0.5000,   0.7000,   0.6000]
                single_pixel:
                    smoothness_constraints: {difference_order: 2, lagrange_multiplier: 0}
            mode[2]:
                initial_guess:
                    index_of_wavelength_involved: [0]
                    max:   [1.0 ]
                    min:   [0.001]
                    value: [0.5 ]
                single_pixel:
                    smoothness_constraints: {difference_order: 1, lagrange_multiplier: 0}
            mode[3]:
                initial_guess:
                    index_of_wavelength_involved: [0]
                    max:   [0.5]
                    min:   [0.00001]
                    value: [0.05]
                single_pixel:
                    smoothness_constraints: {difference_order: 1, lagrange_multiplier: 0}
            retrieved: true
            type: surface_land_brdf_ross_li
        characteristic[8]:
            mode[1]:
                initial_guess:
                    index_of_wavelength_involved: [0]
                    max:   [0.9999999]
                    min:   [0.9990000]
                    value: [0.9999998]
            mode[2]:
                initial_guess:
                    index_of_wavelength_involved: [0]
                    max:   [0.9999999]
                    min:   [0.0000001]
                    value: [0.9999998]
            retrieved: true
            type: sphere_fraction
        characteristic[9]:
            mode[1]:
                initial_guess:
                    index_of_wavelength_involved: [1]
                    max:   [10.0]
                    min:   [1.0]
                    value: [5.0]
                single_pixel:
                    smoothness_constraints: {difference_order: 1, lagrange_multiplier: 10}
            retrieved: true
            type: surface_land_polarized_maignan_breon
        characteristic[10]:
            type: vertical_profile_parameter_standard_deviation
            retrieved: false
            mode[1]:
                initial_guess:                      #1          
                    value:                          [1500.0 ]
                    min:                            [200.0  ] 
                    max:                            [3000.0 ]
                    index_of_wavelength_involved:   [0      ]
            mode[2]:
                initial_guess:                      #1          
                    value:                          [1500.0 ]
                    min:                            [200.0  ] 
                    max:                            [3000.0 ]
                    index_of_wavelength_involved:   [0      ]
