# PSD and n set to match DT absorbing aerosol model (used over central Africa in summer)
# SOURCE: https://agupubs.onlinelibrary.wiley.com/doi/full/10.1029/2006JD007815
# THIS USES NO POLARIZATION COX MUNK!!! (good for OSSE, but not much else)

input: {driver: sdata, file: inversionBACK.sdat}
output:
    segment: {function: classic, stream: bench_inversionRslts.txt}
retrieval:
    constraints:
        characteristic[1]:
            mode[1]:
                initial_guess:
                    index_of_wavelength_involved: [0]
                    max: [0.15]
                    min: [0.00000001]
#                    value: [0.07974]
                    value: [0.075]
                single_pixel:
                    a_priori_estimates:
                        lagrange_multiplier:      [8.0e-5] # NOT TESTED IN IDEAL (only k and Vol unfixed) case
            mode[2]:
                initial_guess:
                    index_of_wavelength_involved: [0]
                    max: [0.09]
                    min: [0.00000001]
#                    value: [0.03884]
                    value: [0.03]
                single_pixel:
                    a_priori_estimates:
                        lagrange_multiplier:      [2.0e-4]
            retrieved: true
            type: aerosol_concentration    
        characteristic[2]:
            mode[1]:
                initial_guess:
                    index_of_wavelength_involved: [1] 
                    max: [0.04]
                    min: [1e-3]
                    value: [0.02] # 0.025 worked well (slight high bias in SSA)
                single_pixel:
                    smoothness_constraints:
                        difference_order: 1
                        lagrange_multiplier: 0.5
                    a_priori_estimates:
                         lagrange_multiplier:      [7.0e-4,7.0e-4,7.0e-4,7.0e-4,7.0e-4,7.0e-4,7.0e-4] # seems less needed with looser land... maybe cut down a bit in multipixel?
            mode[2]:
                initial_guess:
                    index_of_wavelength_involved: [1]
                    max:   [0.026]
                    min:   [0.023]
                    value: [0.024539]
                single_pixel:
                    smoothness_constraints:
                        difference_order: 1
                        lagrange_multiplier: 0.5
            retrieved: true
            type: imaginary_part_of_refractive_index_spectral_dependent
#            type: imaginary_part_of_refractive_index_constant ––– BUG: Many spectral variables do not print right. Does this happen in V1.0?
        characteristic[3]: 
            type: vertical_profile_parameter_height
            retrieved: true
            mode[1]:
                initial_guess:                      #1          
                    value:                          [3000.0 ]
                    min:                            [2700.0] 
                    max:                            [3300.0]
                    index_of_wavelength_involved:   [0      ]
            mode[2]:
                initial_guess:                      #1          
                    value:                          [3000.0 ]
                    min:                            [2700.0] 
                    max:                            [3300.0]
                    index_of_wavelength_involved:   [0      ]
#        VEGITATION INSPIRED 
        characteristic[4]:
            mode[1]:
                initial_guess:
                    index_of_wavelength_involved: [1] #[0.415,  0.470,  0.555,  0.659,  0.865,  1.64,   2.13] μm
                    max:                               [0.0237237, 0.0368368, 0.0722722, 0.0576576, 0.4227223, 0.2459457, 0.1129128]
                    min:                               [0.0236763, 0.0367632, 0.0721278, 0.0575424, 0.4218777, 0.2454543, 0.1126872]
                    value:                             [0.0237,   0.0368,  0.0722,  0.0576,  0.4223,   0.2457,   0.1128] # TRUE
                single_pixel:
                    smoothness_constraints:
                        difference_order: 2
                        lagrange_multiplier: 0
#                    a_priori_estimates:
#                        lagrange_multiplier:      [4.0e-9,4.0e-9,4.0e-9,2.0e-5,4.0e-3,9.0e-3,6.0e-2] # seems less needed with looser land... maybe cut down a bit in multipixel?
            mode[2]:
                initial_guess:
                    index_of_wavelength_involved: [1]
                    max:   [2.000]
                    min:   [0.001]
                    value: [0.6073]
                single_pixel:
                    smoothness_constraints: {difference_order: 1, lagrange_multiplier: 5}
            mode[3]:
                initial_guess:
                    index_of_wavelength_involved: [1]
                    max:   [0.142]
                    min:   [0.140]
                    value: [0.1411]
                single_pixel:
                    smoothness_constraints: {difference_order: 1, lagrange_multiplier: 5}
            retrieved: true
            type: surface_land_brdf_ross_li
        characteristic[5]:
            mode[1]:
                initial_guess:
                    index_of_wavelength_involved: [0, 0]
                    max: [0.34, 0.70]
                    min: [0.07, 0.25]
                    value: [0.13842, 0.41956747]
            mode[2]:
                initial_guess:
                    index_of_wavelength_involved: [0, 0]
                    max: [6.0, 0.8]
                    min: [0.65, 0.25]
                    value: [3.885, 0.76183639]
            retrieved: false
            type: size_distribution_lognormal
        characteristic[6]:
            mode[1]:
                initial_guess:
                    index_of_wavelength_involved: [1] # this should be 1,...,7, what happens with current version?
                    max: [  1.52,       1.52,       1.52,       1.52,       1.52,      1.52,      1.52]
                    min: [  1.47,       1.47,       1.48,       1.49,       1.50,      1.50,      1.50]
                    value: [1.51, 1.51, 1.51, 1.51, 1.51, 1.51, 1.51]
                single_pixel:
                    smoothness_constraints:
                        difference_order: 1
                        lagrange_multiplier: 0.5
            mode[2]:
                initial_guess:
                    index_of_wavelength_involved: [1]
                    max: [  1.52,       1.52,       1.52,       1.52,       1.52,      1.52,      1.52]
                    min: [  1.47,       1.47,       1.48,       1.49,       1.50,      1.50,      1.50]
                    value: [1.51, 1.51, 1.51, 1.51, 1.51, 1.51, 1.51]
                single_pixel:
                    smoothness_constraints:
                        difference_order: 1
                        lagrange_multiplier: 0.5
            retrieved: false
            type: real_part_of_refractive_index_spectral_dependent
#            type: real_part_of_refractive_index_constant            
        characteristic[7]:
            mode[1]:
                initial_guess:
                    index_of_wavelength_involved: [0]
                    max:   [0.9999999]
                    min:   [0.6000000]
                    value: [0.9999998]
            mode[2]:
                initial_guess:
                    index_of_wavelength_involved: [0]
                    max:   [0.9999999]
                    min:    [0.0000001]
                    value: [0.9999998]
            retrieved: false
            type: sphere_fraction
        characteristic[8]:
            mode[1]:
                initial_guess:
                    index_of_wavelength_involved: [1]
                    max:   [0.000003]
                    min:   [0.000001]
                    value: [0.000002]
                single_pixel:
                    smoothness_constraints: {difference_order: 1, lagrange_multiplier: 10}
            retrieved: false
            type: surface_land_polarized_maignan_breon
        characteristic[9]: 
            type: vertical_profile_parameter_standard_deviation
            retrieved: false
            mode[1]:
                initial_guess:                      #1          
                    value:                          [500.0 ]
                    min:                            [200.0  ] 
                    max:                            [3000.0 ]
                    index_of_wavelength_involved:   [0      ]
            mode[2]:
                initial_guess:                      #1          
                    value:                          [500.0 ]
                    min:                            [200.0  ] 
                    max:                            [3000.0 ]
                    index_of_wavelength_involved:   [0      ]
        characteristic[10]:
            type: surface_water_CxMnk_iso_noPol
            retrieved: false
            mode[1]:    
                initial_guess:                       #1      #2      #3      
                    value:                          [0.000000002]
                    min:                            [0.000000001]
                    max:                            [0.000000003]
                    index_of_wavelength_involved:   [1]
                single_pixel:
                    smoothness_constraints:
                        difference_order: 1
                        lagrange_multiplier: 0.0
            mode[2]:
                initial_guess:                       #1      #2      #3 
                    value:                          [0.999999]
                    min:                            [0.999998]
                    max:                            [1.000000]
                    index_of_wavelength_involved:   [0]
            mode[3]:
                initial_guess:                       #1      #2      #3             
                    value:                          [0.015]  
                    min:                            [0.00406] # 1 m/s
                    max:                            [0.040] # 0.027 -> 10 m/s
                    index_of_wavelength_involved:   [0]

    convergence: 
        maximum_iterations_for_stopping: 40
        maximum_iterations_of_Levenberg-Marquardt: 40
        minimization_convention: logarithm
        normal_system_solver: sparse_matrix_solver
        scale_for_finite_difference: 1.0e-05 #2.0e-5
        shift_for_applying_logarithm_to_negative_values: 1.1
        threshold_for_stopping: 1.0e-9 #0.001
        threshold_for_stopping_Q_iterations: 1.0e-09 #1.0e-06
        stop_before_performing_retrieval: false
    debug: {additional_information: false, verbose: true}
    general: {path_to_internal_files: /usr/local/share/grasp/kernels/}
    noises:
        noise[1]:
            error_type: relative
            measurement_type[1]:
                index_of_wavelength_involved: [1]
                type: I
            standard_deviation: 0.03
            standard_deviation_synthetic: 0.0
    phase_matrix:
        kernels_folder: KERNELS_BASE/
        number_of_elements: 4
        radius:
            mode[1]: {max: 15.0, min: 0.05}
            mode[2]: {max: 15.0, min: 0.05}
        size_binning_method_for_triangle_bins: logarithm
    products:
        aerosol: {chemistry: false, lidar: true, optical_properties: true, particulate_matter: false, phase_matrix: false, refractive_index: true, theoretical_bimodal_extinction: false, theoretical_bimodal_parameters: true, type: false}
        error_estimation:
            aerosol: {lidar: false, optical_properties: false}
            parameters: false
        forcing: {broadband_flux: false, forcing: false}
        retrieval: {fitting: true, parameters: true, residual: true}
        surface: true
    radiative_transfer:
        absolute_error_rt_calculations: 1.0e-06
        aerosol_profile_vertical_type: gaussian
        molecular_profile_vertical_type: exponential
        number_of_layers: 50
        reference_plane_for_polarization: meridian
        simulating_derivatives:
            number_of_fourier_expansion_coefficients: 6
            number_of_gaussian_quadratures_for_expansion_coefficients: 10
            number_of_guassian_quadratures_for_fourier_expansion_coefficients: 20
            order_of_scattering: derivatives
        simulating_observation:
            number_of_fourier_expansion_coefficients: 6
            number_of_gaussian_quadratures_for_expansion_coefficients: 10
            number_of_guassian_quadratures_for_fourier_expansion_coefficients: 20
            order_of_scattering: multiple_scattering
    regime_of_measurement_fitting: {polarization: relative_polarization_components}
    regime_of_multipixel_constraints: {inversion_regime: single_pixel}
settings: {strict: true}
