# THIS USES NO POLARIZATION COX MUNK!!! (good for OSSE, but not much else)

settings:
    strict: true
input: {driver: sdata, file: inversionBACK.sdat}
output:
    segment: {function: classic, stream: bench_inversionRslts.txt}
retrieval:
    general: {path_to_internal_files: /usr/local/share/grasp/kernels/}
    mode: inversion
    inversion:
        regime: single_pixel
        convergence:
            maximum_iterations_for_stopping: 20
            maximum_iterations_of_Levenberg-Marquardt: 20
            minimization_convention: logarithm
            normal_system_solver: sparse_matrix_solver
            scale_for_finite_difference: 3.0e-05 #2.0e-5
            shift_for_applying_logarithm_to_negative_values: 1.1
            threshold_for_stopping: 1.0e-9 #0.001
            threshold_for_stopping_Q_iterations: 1.0e-09 #1.0e-06
        measurement_fitting: {polarization: relative_polarization_components}
        noises:
            noise[1]:
                error_type: relative
                measurement_type[1]:
                    index_of_wavelength_involved: [1, 2, 3]
                    type: I
                standard_deviation: 0.03
                standard_deviation_synthetic: 0.0
            noise[2]:
                error_type: absolute
                measurement_type[1]:
                    index_of_wavelength_involved: [1, 2, 3]
                    type: Q
                measurement_type[2]:
                    index_of_wavelength_involved: [1, 2, 3]
                    type: U
                standard_deviation: 0.005
                standard_deviation_synthetic: 0.0
    forward_model:
        phase_matrix:
            kernels_folder: KERNELS_BASE/
            size_binning_method_for_triangle_bins: logarithm
            number_of_elements: 4
            radius:
                mode[1]: {max: 15.0, min: 0.05}
                mode[2]: {max: 15.0, min: 0.05}
        radiative_transfer:
            absolute_error_rt_calculations: 1.0e-06
            aerosol_profile_vertical_type: gaussian
            molecular_profile_vertical_type: exponential
            number_of_layers: 50
            reference_plane_for_polarization: principal_plane
            simulating_derivatives:
                number_of_fourier_expansion_coefficients: 6
                number_of_gaussian_quadratures_for_expansion_coefficients: 8
                number_of_guassian_quadratures_for_fourier_expansion_coefficients: 12
                order_of_scattering: multiple_scattering
            simulating_observation:
                number_of_fourier_expansion_coefficients: 6
                number_of_gaussian_quadratures_for_expansion_coefficients: 8
                number_of_guassian_quadratures_for_fourier_expansion_coefficients: 12
                order_of_scattering: multiple_scattering

    debug:
        additional_information: false
        verbose: true

    products:
        aerosol:
            chemistry: false
            lidar: true
            optical_properties: true
            particulate_matter: false
            phase_matrix: true
            refractive_index: true
            theoretical_bimodal_extinction: false
            theoretical_bimodal_parameters: false
            type: false
        error_estimation:
            aerosol:
                lidar: false
                optical_properties: false
            parameters: false
        forcing:
            broadband_flux: false
            forcing: false
        retrieval:
            fitting: true
            parameters: true
            residual: true
        surface: true

    constraints:
        characteristic[1]:
            type: size_distribution_triangle_bins
            retrieved: true                         # 0.05    ,  0.07163,   0.10242,  0.14704,  0.21048,  0.30154,  0.43216,  0.61456,  0.88758,  1.27403,  1.82419,  2.61089,  3.74474,  5.35806,  7.6777     11    (μm)
            mode[1]:                                # 0.05    ,  0.073133,  0.10697,  0.15646,  0.22884,  0.33472,  0.48957,  0.71608,  1.0474  , 1.5319 ,  2.2407  , 3.2774 ,  4.7937 ,  7.0115  , 10.255   , 15.   (μm)
                initial_guess:                         #1         #2        #3        #4        #5        #6        #7        #8        #9        #10       #11       #12       #13       #14       #15       #16
                      value:                          [0.0005,    0.005,    0.005,    0.005,    0.005,    0.005,    0.005,    0.0005,   0.0005,    0.00005,  0.00005,  0.00005,  0.00005,  0.00005,  0.00005,  0.00005      ]
                      min:                            [0.000005,  0.000005, 0.000005, 0.000005, 0.000005, 0.000005, 0.000005, 0.000005, 0.000005,  0.000005, 0.000005, 0.000005, 0.000005, 0.000005, 0.000005, 0.000005  ]
                      max:                            [0.05,      15.0,     15.0,     15.0,     15.0,     15.0,     15.0,     15.0,     0.005,     0.0001,   0.0001,   0.0001,   0.0001,   0.0001,   0.0001,   0.0001       ]
                      index_of_wavelength_involved:   [0,         0,        0,        0,        0,        0,        0,        0 ,       0,         0,        0,        0,        0,        0,        0,        0         ]
                single_pixel:
                    smoothness_constraints:
                        difference_order: 2
                        lagrange_multiplier: 5.0e-3
            mode[2]:
                initial_guess:                         #1         #2        #3        #4        #5        #6        #7        #8        #9        #10       #11       #12       #13       #14       #15       #16
                      value:                          [0.00005,   0.00005,  0.00005,  0.00005,  0.0005,   0.0089,   0.0099,   0.029,    0.029,    0.029,    0.025,    0.010,    0.005,    0.005,    0.005,    0.0005    ]
                      min:                            [0.000005,  0.000005, 0.000005, 0.000005, 0.000005, 0.000005, 0.000005, 0.000005, 0.000005, 0.000005, 0.000005, 0.000005, 0.000005, 0.000005, 0.000005, 0.000005  ]
                      max:                            [0.0001,    0.0001,   0.0001,   0.01,     0.05,     1.001,    10.001,   15.00,    15.0,     15.0,     15.0,     15.0,     15.0,     15.0,     15.0,     0.005     ]
                      index_of_wavelength_involved:   [0,         0,        0,        0,        0,        0,        0,        0 ,       0,        0,        0,        0,        0,        0,        0,        0         ]
                single_pixel:
                    smoothness_constraints:
                        difference_order: 2
                        lagrange_multiplier: 5.0e-3
        characteristic[2]:
            mode[1]:
                initial_guess:
                    index_of_wavelength_involved: [1]
                    max: [1.65]
                    min: [1.33]
                    value: [1.4]
                single_pixel:
                    smoothness_constraints:
                        difference_order: 1
                        lagrange_multiplier: 4.0
            mode[2]:
                initial_guess:
                    index_of_wavelength_involved: [1]
                    max: [1.65]
                    min: [1.33]
                    value: [1.4]
                single_pixel:
                    smoothness_constraints:
                        difference_order: 1
                        lagrange_multiplier: 2.0
            retrieved: true
            type: real_part_of_refractive_index_spectral_dependent
        characteristic[3]:
            mode[1]:
                initial_guess:
                    index_of_wavelength_involved: [1]
                    max: [0.025]
                    min: [1e-5]
                    value: [0.002]
                single_pixel:
                    smoothness_constraints:
                        difference_order: 2
                        lagrange_multiplier: 0.06
            mode[2]:
                initial_guess:
                    index_of_wavelength_involved: [1]
                    max: [0.025]
                    min: [1e-5]
                    value: [0.002]
                single_pixel:
                    smoothness_constraints:
                        difference_order: 2
                        lagrange_multiplier: 0.06
            retrieved: true
            type: imaginary_part_of_refractive_index_spectral_dependent
        characteristic[4]:
            type: surface_water_CxMnk_iso_noPol
            retrieved: true
            mode[1]:
                initial_guess:                       #1      #2      #3
                    value:                          [0.000000002]
                    min:                            [0.000000001]
                    max:                            [0.000000003]
                    index_of_wavelength_involved:   [1]
                single_pixel:
                    smoothness_constraints:
                        difference_order: 1
                        lagrange_multiplier: 0.0
            mode[2]:
                initial_guess:                       #1      #2      #3
                    value:                          [0.999999]
                    min:                            [0.999998]
                    max:                            [1.000000]
                    index_of_wavelength_involved:   [0]
            mode[3]:
                initial_guess:                       #1      #2      #3
                    value:                          [0.015]
                    min:                            [0.00406] # 1 m/s
                    max:                            [0.040] # 0.027 -> 10 m/s
                    index_of_wavelength_involved:   [0]
        characteristic[5]:
            type: vertical_profile_parameter_height
            retrieved: true
            mode[1]:
                initial_guess:                      #1
                    value:                          [1000.0 ]
                    min:                            [500.0]
                    max:                            [4000.0]
                    index_of_wavelength_involved:   [0      ]
            mode[2]:
                initial_guess:                      #1
                    value:                          [1000.0 ]
                    min:                            [500.0]
                    max:                            [4000.0]
                    index_of_wavelength_involved:   [0      ]
#        DESERT INSPIRED (lower mins)
        characteristic[6]:
            mode[1]:
                initial_guess:
                    index_of_wavelength_involved: [1] # 0.3600, 0.3800, 0.4100, 0.5500, 0.6700, 0.8700, 1.5500, 1.6500 μm
                    max:                               [0.2,     0.2,    0.2,    0.5,   0.7,    0.9,    1.4,    1.4]
                    min:                               [0.0002, 0.0002, 0.0002, 0.0002, 0.0002, 0.0500, 0.0250, 0.020]
                    value:                             [0.0800, 0.0800, 0.0800, 0.2500, 0.3000, 0.4500, 0.6000, 0.6000]
                single_pixel:
                    smoothness_constraints: {difference_order: 2, lagrange_multiplier: 0}
            mode[2]:
                initial_guess:
                    index_of_wavelength_involved: [0]
                    max:   [2.0 ]
                    min:   [0.001]
                    value: [0.1 ]
                single_pixel:
                    smoothness_constraints: {difference_order: 1, lagrange_multiplier: 0}
            mode[3]:
                initial_guess:
                    index_of_wavelength_involved: [0]
                    max:   [1.0]
                    min:   [0.0001]
                    value: [0.1]
                single_pixel:
                    smoothness_constraints: {difference_order: 1, lagrange_multiplier: 0}
            retrieved: true
            type: surface_land_brdf_ross_li
        characteristic[7]:
            mode[1]:
                initial_guess:
                    index_of_wavelength_involved: [0]
                    max:   [0.9999999]
                    min:   [0.9990000]
                    value: [0.9999998]
            mode[2]:
                initial_guess:
                    index_of_wavelength_involved: [0]
                    max:   [0.9999999]
                    min:   [0.0000001]
                    value: [0.9999998]
            retrieved: true
            type: sphere_fraction
        characteristic[8]:
            mode[1]:
                initial_guess:
                    index_of_wavelength_involved: [1]
                    max:   [0.000003]
                    min:   [0.000001]
                    value: [0.000002]
                single_pixel:
                    smoothness_constraints: {difference_order: 1, lagrange_multiplier: 3}
            retrieved: false
            type: surface_land_polarized_maignan_breon
        characteristic[9]:
            type: vertical_profile_parameter_standard_deviation
            retrieved: false
            mode[1]:
                initial_guess:                      #1
                    value:                          [900.0 ]
                    min:                            [250.0  ]
                    max:                            [1500.0 ]
                    index_of_wavelength_involved:   [0      ]
            mode[2]:
                initial_guess:                      #1
                    value:                          [900.0 ]
                    min:                            [250.0  ]
                    max:                            [1500.0 ]
                    index_of_wavelength_involved:   [0      ]
