# YML file for running a backward example of GSFC1 

input: {driver: sdata, file: bench.sdat}
output:
    segment: {function: classic, stream: bench_first_sim_rslts.txt}
retrieval:
    
    general: {path_to_internal_files: /usr/local/share/grasp/kernels/}    
    mode: forward_model
    
    inversion:
        regime: single_pixel
        
        convergence:
            minimization_convention: logarithm
            maximum_iterations_of_Levenberg-Marquardt: 20
            maximum_iterations_for_stopping: 20
            threshold_for_stopping: 1.0e-3
            threshold_for_stopping_Q_iterations: 1.0e-5
            scale_for_finite_difference: 5.0e-3
            shift_for_applying_logarithm_to_negative_values: 1.0
            normal_system_solver: sparse_matrix_solver

        noises:
            noise[1]:
                standard_deviation_synthetic: 0.0
                error_type:  relative
                standard_deviation:  0.005
                measurement_type[1]:
                    type: aod
                    index_of_wavelength_involved: [ 1, 2]

    forward_model:
        phase_matrix:
            size_binning_method_for_triangle_bins: logarithm
            number_of_elements: 0
            kernels_folder: "KERNELS_BASE/"
            radius:
                mode[1]:
                    min: 0.05
                    max: 15.0
                mode[2]:
                    min: 0.05
                    max: 15.0

    products:
        aerosol:
            chemistry: false
            lidar: false
            optical_properties: true
            phase_matrix: false
            refractive_index: true
            theoretical_bimodal_extinction: true
            theoretical_bimodal_parameters: true
        error_estimation:
            aerosol:
                lidar: false
                optical_properties: false
            parameters: false
        forcing:
            broadband_flux: false
            forcing: false
        retrieval:
            fitting: true
            parameters: true
            residual: true

        surface:
            main_characteristics: false

    debug:
        additional_information: false
        verbose: true
        #BB_2101 from OMI paper
    constraints:
        characteristic[1]: 
            type: size_distribution_lognormal
            retrieved: true
            mode[1]: 
                initial_guess: 
                    value:                        [0.145, 0.400]
                    min:                          [0.1,   0.1]
                    max:                          [0.7,   0.9]
                    index_of_wavelength_involved: [0,     0]
                single_pixel:
                    a_priori_estimates:
                        lagrange_multiplier:      [1.0e-03,  1.0e-03]
                    smoothness_constraints:
                        difference_order: 0
                        lagrange_multiplier: 0.0
            mode[2]: 
                initial_guess: 
                    value:                        [3.154, 0.700]
                    min:                          [0.7,   0.1]
                    max:                          [5.0,   0.9]
                    index_of_wavelength_involved: [0,     0]
                single_pixel:
                    a_priori_estimates:
                        lagrange_multiplier:      [1.0e-02,  1.0e-02]
                    smoothness_constraints:
                        difference_order: 0
                        lagrange_multiplier: 0.0

        characteristic[2]: 
            type: aerosol_concentration
            retrieved: true
            mode[1]: 
                initial_guess: 
                    value:                        [0.007]
                    min:                          [0.001]
                    max:                          [0.500]
                    index_of_wavelength_involved: [0]
                single_pixel:
                    a_priori_estimates:
                        lagrange_multiplier:      [0]
                    smoothness_constraints:
                        difference_order: 0
                        lagrange_multiplier: 0.0
            mode[2]: 
                initial_guess: 
                    value:                        [0.001]
                    min:                          [0.001]
                    max:                          [0.500]
                    index_of_wavelength_involved: [0]
                single_pixel:
                    a_priori_estimates:
                        lagrange_multiplier:      [ 0 ]
                    smoothness_constraints:
                        difference_order: 0
                        lagrange_multiplier: 0.0

        characteristic[3]: 
            type: real_part_of_refractive_index_spectral_dependent
            retrieved: true
            mode[1]: 
                initial_guess: 
                    value:                        [1.401,   1.401]
                    min:                          [1.33,    1.33]
                    max:                          [1.6,     1.6]
                    index_of_wavelength_involved: [1,       2]
                single_pixel:
                    a_priori_estimates:
                        lagrange_multiplier:      [0,       0]
                    smoothness_constraints:
                        difference_order: 1
                        lagrange_multiplier: 10.0

        characteristic[4]: 
            type: imaginary_part_of_refractive_index_spectral_dependent
            retrieved: true
            mode[1]: 
                initial_guess: 
                    value:                        [0.0030,  0.0030]
                    min:                          [0.0005,  0.0005]
                    max:                          [0.1,     0.1]
                    index_of_wavelength_involved: [1,       2]
                single_pixel:
                    a_priori_estimates:
                        lagrange_multiplier:      [0,       0]
                    smoothness_constraints:
                        difference_order: 1
                        lagrange_multiplier: 1.e-1

        characteristic[5]: 
            type: sphere_fraction
            retrieved: true
            mode[1]: 
                initial_guess: 
                    value:                        [0.999]
                    min:                          [0.0001]
                    max:                          [0.9999]
                    index_of_wavelength_involved: [0]
                single_pixel:
                    a_priori_estimates:
                        lagrange_multiplier:      [0]
                    smoothness_constraints:
                        difference_order: 0
                        lagrange_multiplier: 0

